@api_HostAddress = http://localhost:5267

GET http://localhost:5267/api/stock

###
GET http://localhost:5267/api/stock?Symbol=MSFT&CompanyName=MICROSOFT

###
GET http://localhost:5267/api/stock?SortBy=Symbol&IsDescending=true

###
GET http://localhost:5267/api/stock?PageNumber=1&PageSize=3

###
GET http://localhost:5267/api/stock/3

###
POST http://localhost:5267/api/stock
Content-Type: application/json

{
   "Symbol" : "TSLA",
   "CompanyName" : "TESLA",
   "Purchase" : "150.00",
   "LastDiv" : "3.7",
   "Industry" : "TECHNOLOGY",
   "MarketCap" : "444272777"
}

###
PUT http://localhost:5267/api/stock/3
Content-Type: application/json

{
   "symbol": "MSFT",
    "companyName": "MICROSOFT",
    "purchase": 96.00,
    "lastDiv": 2.33,
    "industry": "TECHNO",
    "marketCap": 100100103
}

###
DELETE http://localhost:5267/api/stock/7

###
GET http://localhost:5267/api/comment

###
GET http://localhost:5267/api/comment/1

###
POST http://localhost:5267/api/comment/1
Content-Type: application/json

{
   "Title":"TESTING",
   "Content":"Testing Data Validation"
}

###
DELETE  http://localhost:5267/api/comment/4

###
POST http://localhost:5267/api/account/register
Content-Type: application/json

{
   "username":"sujith013",
   "email":"sujith@gmail.com",
   "password":"Abcde12_"
}

###
POST http://localhost:5267/api/account/login
Content-Type: application/json

{
   "username":"sujith013",
   "password":"Abcde12_"
}